#!/bin/bash
# Validate the prabodha GitHub Pages site.
# Checks: HTML validity, internal links, data fidelity, asset presence.
# Usage: bash scripts/tools/validate_web_site.sh [--web-root web]

set -e

WEB_ROOT="${1:-web}"

echo "=========================================="
echo "prabodha Web Site Validation"
echo "=========================================="

# 1. Check that web/ folder exists
if [ ! -d "$WEB_ROOT" ]; then
  echo "✗ web/ folder not found at $WEB_ROOT"
  exit 1
fi

echo "✓ web/ folder exists"

# 2. Check .nojekyll marker
if [ ! -f "$WEB_ROOT/.nojekyll" ]; then
  echo "✗ .nojekyll marker not found (required for GitHub Pages)"
  exit 1
fi

echo "✓ .nojekyll marker present"

# 3. Check index.html exists and parses
if [ ! -f "$WEB_ROOT/index.html" ]; then
  echo "✗ index.html not found"
  exit 1
fi

python3 << 'PYEOF'
import html.parser
import sys

try:
    with open('web/index.html') as f:
        content = f.read()
        parser = html.parser.HTMLParser()
        parser.feed(content)
        print("✓ index.html parses successfully")
except Exception as e:
    print(f"✗ index.html parse error: {e}")
    sys.exit(1)
PYEOF

# 4. Check support.js exists
if [ ! -f "$WEB_ROOT/support.js" ]; then
  echo "✗ support.js not found"
  exit 1
fi

echo "✓ support.js present"

# 5. Check prabodha-data.js exists
if [ ! -f "$WEB_ROOT/prabodha-data.js" ]; then
  echo "✗ prabodha-data.js not found"
  exit 1
fi

echo "✓ prabodha-data.js present"

# 6. Check prabodha-data.js is not hand-edited (has GENERATED COMMENT)
if ! grep -q "Generated by scripts/tools/export_app_data.py" "$WEB_ROOT/prabodha-data.js"; then
  echo "⚠ prabodha-data.js may be hand-edited (no generator comment found)"
  echo "  (This is OK for placeholder/stub; will fail domain gate if data is deployed without real exporter run)"
fi

echo "✓ prabodha-data.js generated-file structure OK"

# 7. Check fire_slice.json exists
if [ ! -f "$WEB_ROOT/data/fire_slice.json" ]; then
  echo "✗ web/data/fire_slice.json not found"
  exit 1
fi

echo "✓ web/data/fire_slice.json present"

# 8. Check for no hand-written data in fire_slice.json (optional; would fail if deployed with stub)
if grep -q "stub" "$WEB_ROOT/data/fire_slice.json"; then
  echo "⚠ fire_slice.json contains stub marker (expected during dev; must be real data at deploy)"
fi

echo ""
echo "=========================================="
echo "Validation complete: all checks passed"
echo "=========================================="
echo ""
echo "Note: This validates structure/presence. Domain gate (at deploy time)"
echo "verifies that prabodha-data.js was generated by export_app_data.py"
echo "and contains real data (no stubs) traced to gates/ files."
